name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=1.20.2
  - ipython=7.28.0
  - notebook=6.4.4
  - jupyterlab=3.2.0
  - cookiecutter=1.7.3
  - hydra-core=0.11.3
  - matplotlib=3.4.3
  - pandas=1.3.3
  - wandb=0.10.31