name: train_random_forest
channels:
  - conda-forge
  - conda-forge/label/broken
  - defaults
dependencies:
  - pandas=1.3.3
  - mlflow=1.20.2
  - scikit-learn=0.24.1
  - matplotlib=3.4.3
  - pillow=8.1.2
  - wandb=0.10.31